baseurl = "https://ilvidel.quijost.com"
title = "Nacheras en Bristol"
languageCode = "es-ES"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-56289011-2" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Ignacio Díez"
    bio = "Un tonto viviendo en Bristol. Y encima, lo cuenta."
    avatar = "images/logo.jpg"

[Params]
    subtitle = "Turismo y Tonterías" # Subtitle of your site
    description = "Curiosidades y otras memeces sobre mi vida en Bristol" # Description of your site
    opengraph = true
    leftsidebar = true # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true

[Params.widgets]
    search = false # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget