baseurl = "https://ilvidel.quijost.com"
languageCode = "es-es"
title = "Nacheras en Bristol"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-56289011-2"
paginate=10

[params]
	# General information
	author = "Ignacio D&iacute;ez"
	description = "Turismo y Curiosidades"
	copyright = "Released under the Creative Commons BY-NC-SA license"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "pink"
    	accent  = "cyan"

    [params.font]
    	text = "Oxygen" # choose from https://fonts.google.com
    	code = "Ubuntu Mono"


[social]
	twitter = "ilvidel"
	# github  = "digitalcraftsman"
	# email   = "hello@email.com"


[[menu.main]]
	name   = "Sobre mi"
	url    = "about/"
	weight = 0

[[menu.main]]
	name   = "Posts"
	url    = "post/"
	weight = 10

# [[menu.main]]
# 	name   = "License"
# 	url    = "license/"
# 	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
