baseurl = "https://ilvidel.quijost.com/"
languageCode = "es-es"
title = "Nacheras en Bristol"
theme = "blackburn"
author = "Ignacio D&iacute;ez"
copyright = "(C) Creative Commons BY-NC-SA"
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"
  categories = "categories"

[params]
  # Shown in the home page
  subtitle = "Turismo y Curiosidades"
  brand = "Blackburn"
  googleAnalytics = "UA-56289011-2"
  # disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "posts"
    url = "/posts/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  # [[menu.main]]
  #   name = "Contact"
  #   pre = "<i class='fa fa-phone fa-fw'></i>"
  #   weight = 3
  #   url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "ilvidel"
  # facebook = "*"
  # instagram = "*"
  # github = "yoshiharuyamashita"
  # stackoverflow = "*"
  # linkedin = "*"
