baseurl = "http://ilvidel.github.io/"
languageCode = "es-es"
title = "Viviendo en Bristol"
# paginate = "5" # Number of posts per page
theme = "mainroad"
# disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-56289011-2" # Enable Google Analytics by entering your tracking id

[author]
    name = "Ignacio Díez"
    bio = "Un tonto viviendo en Bristol. Y encima, lo cuenta."
    avatar = "img/avatar.png"

[Params]
    description = "Curiosidades y otras memeces sobre mi vida en Bristol" # Description of your site
 	authorbox = true # Show authorbox at bottom of pages if true
 	opengraph = true # Enable OpenGraph if true
 	schema = true # Enable Schema
	twitter_cards = true # Enable Twitter Cards if true
 	readmore = false # Show "Read more" button in list if true
	toc = true # Enable Table of Contents
	pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
	post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
	mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
	dateformat = "2006-01-02" # Change the format of dates
	#mathjax = true # Enable MathJax
	#mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
	#mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
	googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
	#customCSS = ["css/custom.css"] # Include custom CSS files
	#customJS = ["js/custom.js"] # Include custom JS files

[Params.logo]
	subtitle = "Turismo y Tonterías"
	# image = "img/placeholder.jpg" # Logo image. Path relative to "static"
 	title = "Mainroad" # Logo title, otherwise will use site title

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color
  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"


[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  # widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  widgets = ["search", "recent", "categories", "social", "languages"]

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
